"""added special instructions field to Order model

Revision ID: 02c8e70463a8
Revises: 256b15f4e1ba
Create Date: 2023-12-21 22:30:06.665303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c8e70463a8'
down_revision = '256b15f4e1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_instr', sa.Text(), nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.INTEGER(), nullable=True))
        batch_op.drop_column('special_instr')

    # ### end Alembic commands ###
