"""linked orders and reviews (messages)

Revision ID: 256b15f4e1ba
Revises: a0f6104b128b
Create Date: 2023-12-21 21:30:14.051177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256b15f4e1ba'
down_revision = 'a0f6104b128b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_id', 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_id', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
