"""added reviewed field to orders model

Revision ID: 3c8e1dd82af7
Revises: 19c77a084ae5
Create Date: 2023-12-21 20:46:53.697974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8e1dd82af7'
down_revision = '19c77a084ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('reviewed')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
