"""removed delivery date from order model

Revision ID: 6d6be3ef3c82
Revises: 3c8e1dd82af7
Create Date: 2023-12-21 21:13:52.729016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6be3ef3c82'
down_revision = '3c8e1dd82af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
