"""changed reviewed from str to bool

Revision ID: a0f6104b128b
Revises: 6d6be3ef3c82
Create Date: 2023-12-21 21:22:10.209821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f6104b128b'
down_revision = '6d6be3ef3c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('reviewed',
               existing_type=sa.VARCHAR(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('reviewed',
               existing_type=sa.BOOLEAN(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
