"""changed status to boolean

Revision ID: f788ab0a5b1d
Revises: c380fd2d2099
Create Date: 2023-11-19 12:36:57.173780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f788ab0a5b1d'
down_revision = 'c380fd2d2099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
